#!/usr/bin/env bash

# Add bash completion for git and a ton of other commands
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi

# Best ls
alias ls="gls -lh --color=auto --group-directories-first"

# Now with hidden files
alias la="ls -A"

alias boop="touch"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Show/hide hidden files in Finder
alias showhiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehiddenfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias notify="tput bel"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
    alias "$method"="lwp-request -m '$method'"
done

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Rain or shine
alias weather='open https://darksky.net'

# Bash/Zsh and dir commands
alias rb="source ~/.bash_profile"
alias rz="source ~/.zshrc"
alias dev="cd ~/dev"
alias dot="nova ~/dev/dotfiles"

# Put just the display to sleep
alias zzz="pmset displaysleepnow"  # Just for touchbar Macs

# Run benchmark for Bash prompt
alias bench="__bashrc_bench=1 bash ~/dev/dotfiles/terminal/benchmark.sh"

# Git commands
alias gcl="git clone"
alias gl="git log"
alias glf="git log --format=full"
alias gs="git status"
alias ga="git add -A"
alias gco="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gb="git branch"
alias gnb="git checkout -b"
alias gch="git checkout"
__git_complete gch _git_checkout
alias gm="git merge"
alias gac="git add -A && git commit -m"
alias gst="git stash"
alias gstl="git stash list"
alias gsp="git stash pop"

# Docker commands
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias dcp="docker-compose ps"
alias dck="docker-compose kill"
alias dcr="docker-compose rm"
alias dil="docker image ls"
alias dip="docker image prune"

#  Restarting a specific container (say, after a new package has been added to a container) - 
#  modified from here: https://stackoverflow.com/a/36885311/7465749
#    1. docker-compose ps # lists all services (id, name)
#    2. docker-compose kill # just stop all containers
#    3. docker-compose rm <id/name> # this will remove the docker container permanently 
#    4. docker-compose build <id/name> # this will rebuild the docker container and install the new
#       packages
#    5. docker-compose up # builds/rebuilds all not already built container
#  
#  NOTE: the id/name here is the name of the container - docker-compose bases the project name on
#  the basename of the directory compose commands are run from, stated in docker-compose issue #745
#  (https://github.com/docker/compose/issues/745). So, by default, you'll probably see some sort of
#  ouput like <dirname>_<container-name>_<instance-number>. The container-name is what you need to
#  input in the above commands - you don't need anything else. Helpful SO post:
#  https://stackoverflow.com/questions/33045358/docker-compose-image-named-prefix-s-1-instead-of-s

#  If you run into a Postgres issue with docker-compose, along the lines of an error that reads
#  "The data directory was initialized by PostgreSQL version X, which is not compatible with
#  this version Y", this is an issue with the VOLUME (something I still need to better understand).
#  To fix this issue:
#    1. docker-compose kill # stop all containers
#    2. docker-compose ps # list all the services that are running, and find your DB service
#    3. docker-compose rm <id/name> # remove the specific DB service
#    4. docker volume ls # list all the volumes on your machine, and locate your DB volume (hopefully
#       named something similar to your service)
#    5. docker volume rm <name> # remove the DB volume
#  More info here: https://stackoverflow.com/a/58146616/7465749