#!/usr/bin/env bash

export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

if [ -f $(brew --prefix coreutils)/libexec/gnubin ]; then
    export PATH="`$(brew --prefix coreutils)/libexec/gnubin`:$PATH"
fi
if [ -f $(brew --prefix findutils)/libexec/gnubin ]; then
    export PATH="`$(brew --prefix findutils)/libexec/gnubin`:$PATH"
fi

export PATH="~/.bash/bin:$PATH"
